(function (maps) {
    var proto = FullScreenMario.prototype.settings.maps.maps = {},
        mapName;
    
    for(mapName in maps) {
        if(maps.hasOwnProperty(mapName)) {
            proto[mapName] = maps[mapName];
        }
    }
})({
    "1-1": {
        "locations": [
              { "entry": "Plain" },
              { "entry": "PipeVertical" },
              { "area": 1 },
        ],
        "areas": [
            {
                "setting": "Overworld",
                "creation": [
                    { "location": 0 },
                    { "macro": "Pattern", "pattern": "BackRegular", "repeat": 5 },
                    { "macro": "Floor", "width": 552 },
                    { "thing": "Block", "x": 128, "y": 32 },
                    { "thing": "Brick", "x": 160, "y": 32 },
                    { "thing": "Block", "x": 168, "y": 32, "contents": "Mushroom" },
                    { "thing": "Goomba", "x": 176, "y": 8 },
                    { "thing": "Brick", "x": 176, "y": 32 },
                    { "thing": "Block", "x": 176, "y": 64 },
                    { "thing": "Block", "x": 184, "y": 32 },
                    { "thing": "Brick", "x": 192, "y": 32 },
                    { "macro": "Pipe", "x": 224, "height": 16 },
                    { "macro": "Pipe", "x": 304, "height": 24 },
                    { "macro": "Pipe", "x": 368, "height": 32 },
                    { "thing": "Goomba", "x": 340, "y": 8 },
                    { "macro": "Pipe", "x": 368, "height": 32 },
                    { "thing": "Goomba", "x": 412, "y": 8 },
                    { "thing": "Goomba", "x": 422, "y": 8 },
                    { "macro": "Pipe", "x": 456, "height": 32, "transport": 2 },
                    { "thing": "Block", "x": 512, "y": 40, "contents": "Mushroom1Up", "hidden": true },
                    { "macro": "Floor", "x": 568, "width": 120 },
                    { "thing": "Brick", "x": 616, "y": 32 },
                    { "thing": "Block", "x": 624, "y": 32, "contents": "Mushroom" },
                    { "thing": "Brick", "x": 632, "y": 32 },
                    { "thing": "Brick", "x": 640, "y": 32 },
                    { "thing": "Goomba", "x": 640, "y": 72 },
                    { "thing": "Brick", "x": 648, "y": 64 },
                    { "thing": "Brick", "x": 656, "y": 64 },
                    { "thing": "Goomba", "x": 656, "y": 72 },
                    { "macro": "Fill", "thing": "Brick", "x": 664, "y": 64, "xnum": 5, "xwidth": 8 },
                    { "macro": "Floor", "x": 712, "width": 512 }, 
                    { "macro": "Fill", "thing": "Brick", "x": 728, "y": 64, "xnum": 3, "xwidth": 8 },
                    { "thing": "Brick", "x": 752, "y": 32, "contents": "Coin" },
                    { "thing": "Block", "x": 752, "y": 64 },
                    { "thing": "Goomba", "x": 776, "y": 8 },
                    { "thing": "Goomba", "x": 788, "y": 8 },
                    { "thing": "Brick", "x": 800, "y": 32 },
                    { "thing": "Brick", "x": 808, "y": 32, "contents": "Star" },
                    { "thing": "Block", "x": 848, "y": 32 },
                    { "thing": "Koopa", "x": 856, "y": 12 },
                    { "thing": "Block", "x": 872, "y": 32 },
                    { "thing": "Block", "x": 872, "y": 64, "contents": "Mushroom" },
                    { "thing": "Block", "x": 896, "y": 32 },
                    { "thing": "Goomba", "x": 912, "y": 8 },
                    { "thing": "Goomba", "x": 924, "y": 8 },
                    { "thing": "Brick", "x": 944, "y": 32 },
                    { "macro": "Fill", "thing": "Brick", "x": 968, "y": 64, "xnum": 3, "xwidth": 8 },
                    { "macro": "Fill", "thing": "Goomba", "x": 992, "y": 8, "xnum": 4, "xwidth": 16 },
                    { "thing": "Brick", "x": 1024, "y": 64 },
                    { "thing": "Brick", "x": 1032, "y": 32 },
                    { "thing": "Block", "x": 1032, "y": 64 },
                    { "thing": "Brick", "x": 1040, "y": 32 },
                    { "thing": "Block", "x": 1040, "y": 64 },
                    { "thing": "Brick", "x": 1048, "y": 64 },
                    { "thing": "Stone", "x": 1072, "y": 8 },
                    { "thing": "Stone", "x": 1080, "y": 16, "height": 16 },
                    { "thing": "Stone", "x": 1088, "y": 24, "height": 24 },
                    { "thing": "Stone", "x": 1096, "y": 32, "height": 32 },
                    { "thing": "Stone", "x": 1120, "y": 32, "height": 32 },
                    { "thing": "Stone", "x": 1128, "y": 24, "height": 24 },
                    { "thing": "Stone", "x": 1136, "y": 16, "height": 16 },
                    { "thing": "Stone", "x": 1144, "y": 8 },
                    { "thing": "Stone", "x": 1184, "y": 8 },
                    { "thing": "Stone", "x": 1192, "y": 16, "height": 16 },
                    { "thing": "Stone", "x": 1200, "y": 24, "height": 24 },
                    { "thing": "Stone", "x": 1208, "y": 32, "height": 32 },
                    { "thing": "Stone", "x": 1216, "y": 32, "height": 32 },
                    { "macro": "Floor", "x": 1240, "width": 656 },
                    { "thing": "Stone", "x": 1240, "y": 32, "height": 32 },
                    { "thing": "Stone", "x": 1248, "y": 24, "height": 24 },
                    { "thing": "Stone", "x": 1256, "y": 16, "height": 16 },
                    { "thing": "Stone", "x": 1264, "y": 8 },
                    { "macro": "Pipe", "x": 1304, "height": 16, "entrance": 1 },
                    { "thing": "Brick", "x": 1344, "y": 32 },
                    { "thing": "Brick", "x": 1352, "y": 32 },
                    { "thing": "Block", "x": 1360, "y": 32 },
                    { "thing": "Brick", "x": 1368, "y": 32 },
                    { "thing": "Goomba", "x": 1392, "y": 8 },
                    { "thing": "Goomba", "x": 1404, "y": 8 },
                    { "macro": "Pipe", "x": 1432, "height": 16 },
                    { "thing": "Stone", "x": 1448, "y": 8 },
                    { "thing": "Stone", "x": 1456, "y": 16, "height": 16 },
                    { "thing": "Stone", "x": 1464, "y": 24, "height": 24 },
                    { "thing": "Stone", "x": 1472, "y": 32, "height": 32 },
                    { "thing": "Stone", "x": 1480, "y": 40, "height": 40 },
                    { "thing": "Stone", "x": 1488, "y": 48, "height": 48 },
                    { "thing": "Stone", "x": 1496, "y": 56, "height": 56 },
                    { "thing": "Stone", "x": 1504, "y": 64, "height": 64, "width": 16 },
                    { "macro": "EndOutsideCastle", "x": 1584, "y": 0 }
                ]
            },
            {
                "setting": "Underworld",
                "creation": [
                    { "location": 2 },
                    { "macro": "Ceiling", "x": 32, "width": 56 },
                    { "macro": "Floor", "x": 0, "y": 0, "width": 136 },
                    { "macro": "Fill", "thing": "Brick", "x": 0, "y": 8, "ynum": 11, "yheight": 8 },
                    { "macro": "Fill", "thing": "Brick", "x": 32, "y": 8, "xnum": 7, "ynum": 3, "xwidth": 8, "yheight": 8 },
                    { "macro": "Fill", "thing": "Coin", "x": 33, "y": 31, "xnum": 7, "ynum": 2, "xwidth": 8, "yheight": 16 },
                    { "macro": "Fill", "thing": "Coin", "x": 41, "y": 63, "xnum": 5, "ynum": 1, "xwidth": 8 },
                    { "thing": "PipeHorizontal", "x": 104, "y": 16, "transport": 1, "width": 16 },
                    { "thing": "PipeVertical", "x": 120, "y": 88, "height": 88 }
                ]
            }
        ]
    },
    "1-2": {
        "locations": [
            { "entry": "Walking" },
            { "area": 1 },
            { "area": 2 },
            { "area": 1, "entry": "PipeVertical" },
            { "area": 3, "entry": "PipeVertical" },
            { "area": 1 }
        ],
        "areas": [
            {
                "setting": "Overworld",
                "creation": [
                    { "location": 0 },
                    { "macro": "Pattern", "pattern": "BackCloud", "y": 4, "repeat": 1 },
                    { "macro": "Floor", "width": 192 },
                    { "thing": "PipeHorizontal", "x": 80, "y": 16, "transport": 1 },
                    { "macro": "Pipe", "x": 96, "height": 32 }
                ]
            },
            {
                "setting": "Underworld",
                "creation": [
                    { "location": 1 },
                    { "macro": "Floor", "width": 640 },
                    { "macro": "Fill", "thing": "Brick", "y": 8, "ynum": 11 },
                    { "macro": "Ceiling", "x": 48, "width": 664 },
                    { "thing": "Block", "x": 80, "y": 32, "contents": "Mushroom" },
                    { "macro": "Fill", "thing": "Block", "x": 88, "y": 32, "xnum": 4 },
                    { "thing": "Goomba", "x": 128, "y": 8 },
                    { "thing": "Stone", "x": 136, "y": 8 },
                    { "thing": "Goomba", "x": 136, "y": 16 },
                    { "thing": "Stone", "x": 152, "y": 16, "height": 16 },
                    { "thing": "Stone", "x": 168, "y": 24, "height": 24 },
                    { "thing": "Stone", "x": 184, "y": 32, "height": 32 },
                    { "thing": "Stone", "x": 200, "y": 32, "height": 32 },
                    { "thing": "Stone", "x": 216, "y": 24, "height": 24 },
                    { "thing": "Goomba", "x": 232, "y": 8 },
                    { "thing": "Brick", "x": 232, "y": 40, "contents": "Coin" },
                    { "thing": "Stone", "x": 248, "y": 24, "height": 24 },
                    { "thing": "Stone", "x": 264, "y": 16, "height": 16 },
                    { "macro": "Fill", "thing": "Brick", "x": 312, "y": 32, "ynum": 3 },
                    { "thing": "Brick", "x": 320, "y": 32 },
                    { "thing": "Coin", "x": 321, "y": 39 },
                    { "macro": "Fill", "thing": "Brick", "x": 328, "y": 32, "ynum": 3 },
                    { "macro": "Fill", "thing": "Coin", "x": 330, "y": 60, "xnum": 4, "xwidth": 8 },
                    { "thing": "Brick", "x": 336, "y": 48 },
                    { "thing": "Brick", "x": 344, "y": 48 },
                    { "macro": "Fill", "thing": "Koopa", "x": 352, "y": 12, "xnum": 2, "xwidth": 12 },
                    { "macro": "Fill", "thing": "Brick", "x": 352, "y": 32, "ynum": 3 },
                    { "thing": "Brick", "x": 360, "y": 32 },
                    { "thing": "Coin", "x": 361, "y": 39 },
                    { "macro": "Fill", "thing": "Brick", "x": 368, "y": 32, "ynum": 2 },
                    { "thing": "Brick", "x": 368, "y": 48, "contents": "Star" },
                    { "macro": "Fill", "thing": "Brick", "x": 416, "y": 32, "xnum": 2, "ynum": 5 },
                    { "macro": "Fill", "thing": "Brick", "x": 432, "y": 16, "xnum": 2, "ynum": 3 },
                    { "macro": "Fill", "thing": "Brick", "x": 432, "y": 72, "xnum": 2, "ynum": 2 },
                    { "macro": "Fill", "thing": "Brick", "x": 464, "y": 32, "xnum": 4, "ynum": 1 },
                    { "macro": "Fill", "thing": "Brick", "x": 464, "y": 72, "xnum": 5, "ynum": 2 },
                    { "macro": "Fill", "thing": "Coin", "x": 465, "y": 39, "xnum": 4, "xwidth": 8 },
                    { "thing": "Koopa", "x": 472, "y": 12 },
                    { "macro": "Fill", "thing": "Brick", "x": 496, "y": 32, "xnum": 2, "ynum": 7 },
                    { "thing": "Goomba", "x": 494, "y": 8 },
                    { "thing": "Goomba", "x": 510, "y": 8 },
                    { "macro": "Fill", "thing": "Brick", "x": 528, "y": 72, "xnum": 4, "ynum": 2 },
                    { "macro": "Fill", "thing": "Brick", "x": 536, "y": 32, "ynum": 5 },
                    { "macro": "Fill", "thing": "Brick", "x": 544, "y": 32, "xnum": 2 },
                    { "thing": "Coin", "x": 545, "y": 39 },
                    { "thing": "Brick", "x": 552, "y": 40, "contents": "Mushroom" },
                    { "macro": "Fill", "thing": "Brick", "x": 576, "y": 32, "xnum": 2 },
                    { "thing": "Brick", "x": 576, "y": 40 },
                    { "macro": "Fill", "thing": "Brick", "x": 576, "y": 48, "xnum": 2, "ynum": 3 },
                    { "thing": "Brick", "x": 584, "y": 40, "contents": "Coin" },
                    { "thing": "Goomba", "x": 584, "y": 72 },
                    { "macro": "Fill", "thing": "Brick", "x": 608, "y": 32, "xnum": 4 },
                    { "macro": "Fill", "thing": "Goomba", "x": 608, "y": 40, "xnum": 2, "xwidth": 12 },
                    { "macro": "Fill", "thing": "Brick", "x": 608, "y": 72, "xnum": 4, "ynum": 2 },
                    { "macro": "Floor", "x": 664, "width": 272 },
                    { "macro": "Fill", "thing": "Brick", "x": 672, "y": 40, "xnum": 6, "ynum": 2 },
                    { "macro": "Fill", "thing": "Coin", "x": 674, "y": 64, "xnum": 6, "xwidth": 8 },
                    { "thing": "Brick", "x": 712, "y": 88, "contents": "Mushroom1Up" },
                    { "macro": "Ceiling", "x": 720, "width": 360 },
                    { "macro": "Fill", "thing": "Goomba", "x": 768, "y": 8, "xnum": 3, "xwidth": 12 },
                    { "macro": "Pipe", "x": 800, "height": 24, "piranha": true, "transport": 2 },
                    { "macro": "Pipe", "x": 848, "height": 32, "piranha": true },
                    { "thing": "Goomba", "x": 872, "y": 8 },
                    { "macro": "Pipe", "x": 896, "height": 16, "piranha": true, "entrance": 3 },
                    { "macro": "Floor", "x": 952, "width": 16 },
                    { "macro": "Fill", "thing": "Brick", "x": 952, "y": 8, "xnum": 2, "ynum": 3 },
                    { "macro": "Floor", "x": 984, "width": 96 },
                    { "thing": "Stone", "x": 1040, "y": 8 },
                    { "thing": "Stone", "x": 1048, "y": 16, "height": 16 },
                    { "thing": "Stone", "x": 1056, "y": 24, "height": 24 },
                    { "thing": "Goomba", "x": 1056, "y": 32 },
                    { "thing": "Stone", "x": 1064, "y": 32, "height": 32 },
                    { "thing": "Goomba", "x": 1064, "y": 48 },
                    { "thing": "Stone", "x": 1072, "y": 32, "height": 32 },
                    { "macro": "PlatformGenerator", "x": 1096, "width": 6 },
                    { "macro": "Floor", "x": 1144, "width": 64 },
                    { "macro": "Fill", "thing": "Brick", "x": 1144, "y": 40, "xnum": 5, "ynum": 1 },
                    { "thing": "Koopa", "x": 1152, "y": 12, "smart": true },
                    { "thing": "Brick", "x": 1184, "y": 40, "contents": "Mushroom" },
                    { "macro": "PlatformGenerator", "x": 1224, "width": 6, "direction": -1 },
                    { "macro": "Floor", "x": 1266,  "width": 256 },
                    { "macro": "Fill", "thing": "Brick", "x": 1266, "y": 8, "xnum": 17, "ynum": 3 },
                    { "thing": "PipeHorizontal", "x": 1314, "y": 40, "transport": 4 },
                    { "thing": "PipeVertical", "x": 1330, "y": 88, "height": 64 },
                    { "macro": "Ceiling", "x": 1274, "width": 56 },
                    { "macro": "Fill", "thing": "Brick", "x": 1346, "y": 32, "xnum": 7, "ynum": 7 },
                    { "macro": "Ceiling", "x": 1346, "width": 136 },
                    { "thing": "ScrollBlocker", "x": 1346 },
                    { "macro": "WarpWorld", "x": 1400, "warps": [4, 3, 2] },
                    { "macro": "Fill", "thing": "Brick", "x": 1506, "y": 8, "xnum": 2, "ynum": 11 }
                ]
            },
            {
                "setting": "Underworld",
                "creation": [
                    { "location": 2 },
                    { "macro": "Floor", "width": 136 },
                    { "macro": "Fill", "thing": "Brick", "y": 8, "ynum": 11 },
                    { "macro": "Fill", "thing": "Brick", "x": 24, "y": 32, "xnum": 9 },
                    { "macro": "Fill", "thing": "Brick", "x": 24, "y": 64, "xnum": 10, "ynum": 4 },
                    { "macro": "Fill", "thing": "Coin", "x": 25, "y": 7, "xnum": 9, "xwidth": 8 },
                    { "macro": "Fill", "thing": "Coin", "x": 33, "y": 39, "xnum": 8, "xwidth": 8 },
                    { "thing": "Brick", "x": 96, "y": 32, "contents": "Coin" },
                    { "macro": "Fill", "thing": "Brick", "x": 104, "y": 24, "xnum": 2, "ynum": 9 },
                    { "thing": "PipeHorizontal", "x": 104, "y": 16, "transport": 3 },
                    { "thing": "PipeVertical", "x": 120, "y": 100, "height": 100 }
                ]
            },
            {
                "setting": "Overworld",
                "creation": [
                    { "location": 4 },
                    { "macro": "Floor", "width": 464 },
                    { "macro": "Pipe", "height": 16, "piranha": true, "entrance": 4 },
                    { "macro": "Pattern", "pattern": "BackRegular", "x": 104, },
                    { "thing": "Stone", "x": 16, "y": 8 },
                    { "thing": "Stone", "x": 24, "y": 16, "height": 16 },
                    { "thing": "Stone", "x": 32, "y": 24, "height": 24 },
                    { "thing": "Stone", "x": 40, "y": 32, "height": 32 },
                    { "thing": "Stone", "x": 48, "y": 40, "height": 40 },
                    { "thing": "Stone", "x": 56, "y": 48, "height": 48 },
                    { "thing": "Stone", "x": 64, "y": 56, "height": 56 },
                    { "thing": "Stone", "x": 72, "y": 64, "height": 64 },
                    { "macro": "EndOutsideCastle", "x": 148 }
                ]
            }
        ]
    },
    "1-3": {
        "time": 300,
        "locations": [
            { "entry": "Plain" }
        ],
        "areas": [
            {
                "setting": "Overworld",
                "creation": [
                    { "location": 0 },
                    { "macro": "Pattern", "pattern": "BackCloud", "x": 0, "y": 4, "repeat": 5 },
                    { "macro": "Floor", "x": 0, "y": 0, "width": 128 },
                    { "macro": "Tree", "x": 144, "y": 8, "width": 32 },
                    { "macro": "Tree", "x": 192, "y": 32, "width": 64 },
                    { "macro": "Tree", "x": 208, "y": 64, "width": 40 },
                    { "macro": "Fill", "thing": "Coin", "x": 217, "y": 71, "xnum": 3, "xwidth": 8 },
                    { "thing": "Koopa", "x": 240, "y": 76, "smart": true },
                    { "macro": "Tree", "x": 256, "y": 8, "width": 24 },
                    { "thing": "Coin", "x": 266, "y": 15 },
                    { "macro": "Tree", "x": 280, "y": 40, "width": 40 },
                    { "macro": "Fill", "thing": "Coin", "x": 297, "y": 87, "xnum": 2, "xwidth": 8 },
                    { "macro": "Tree", "x": 320, "y": 72, "width": 56 },
                    { "macro": "Fill", "thing": "Goomba", "x": 352, "y": 80, "xnum": 2, "xwidth": 16 },
                    { "macro": "Tree", "x": 400, "width": 32 },
                    { "macro": "Fill", "thing": "Coin", "x": 402, "y": 55, "xnum": 2, "xwidth": 8 },
                    { "thing": "Platform", "x": 440, "y": 56, "width": 24, "floating": true, "begin": -4, "end": 56 },
                    { "macro": "Tree", "x": 472, "width": 40 },
                    { "thing": "Block", "x": 472, "y": 24, "contents": "Mushroom" },
                    { "macro": "Tree", "x": 480, "y": 64, "width": 32 },
                    { "macro": "Fill", "thing": "Coin", "x": 482, "y": 71, "xnum": 4, "xwidth": 8 },
                    { "macro": "Tree", "x": 520, "width": 40 },
                    { "macro": "Tree", "x": 560, "y": 32, "width": 24 },
                    { "thing": "Koopa", "x": 592, "y": 76, "smart": true, "jumping": true, "floating": true, "begin": 16, "end": 88 },
                    { "macro": "Tree", "x": 608, "y": 56, "width": 48 },
                    { "thing": "Goomba", "x": 640, "y": 64 },
                    { "macro": "Fill", "thing": "Coin", "x": 681, "y": 63, "xnum": 2, "xwidth": 8 },
                    { "thing": "Platform", "x": 688, "y": 40, "width": 24, "sliding": true, "begin": 660, "end": 720 },
                    { "macro": "Fill", "thing": "Coin", "x": 745, "y": 71, "xnum": 2, "xwidth": 8 },
                    { "thing": "Platform", "x": 752, "y": 32, "width": 24, "sliding": true, "begin": 770, "end": 776 },
                    { "macro": "Fill", "thing": "Coin", "x": 777, "y": 71, "xnum": 2, "xwidth": 8 },
                    { "macro": "Tree", "x": 784, "y": 16, "width": 32 },
                    { "macro": "Tree", "x": 832, "y": 48, "width": 64 },
                    { "thing": "Koopa", "x": 880, "y": 60, "smart": true },
                    { "macro": "Tree", "x": 904, "width": 24 },
                    { "macro": "Fill", "thing": "Coin", "x": 906, "y": 7, "xnum": 3, "xwidth": 8 },
                    { "thing": "Koopa", "x": 912, "y": 68, "smart": true, "jumping": true, "floating": true, "begin": 4, "end": 76 },
                    { "macro": "Tree", "x": 928, "y": 32, "width": 32 },
                    { "macro": "Fill", "thing": "Coin", "x": 963, "y": 63, "xnum": 2, "xwidth": 8 },
                    { "macro": "Tree", "x": 976, "y": 32, "width": 32 },
                    { "macro": "Floor", "x": 1032, "width": 368 },
                    { "thing": "Platform", "x": 1048, "y": 56, "width": 24, "sliding": true, "begin": 1008, "end": 1076 },
                    { "thing": "Koopa", "x": 1064, "y": 12, "smart": true },
                    { "thing": "Stone", "x": 1104, "y": 32, "width": 16, "height": 32 },
                    { "thing": "Stone", "x": 1120, "y": 48, "width": 16, "height": 48 },
                    { "thing": "Stone", "x": 1136, "y": 64, "width": 16, "height": 64 },
                    { "macro": "EndOutsideCastle", "x": 1220, "big": true, "wallwidth": 88 }
                ]
            }
        ]
    },
    "1-4": {
        "time": 300,
        "locations": [
            { "entry": "Castle" }
        ],
        "areas": [
            {
                "setting": "Castle",
                "creation": [
                    { "location": 0 },
                    { "macro": "StartInsideCastle", "width": 104 },
                    { "thing": "Stone", "y": 88, "width": 192, "height": 24 },
                    { "macro": "Water", "x": 104, "y": 8, "width": 24 },
                    { "macro": "Floor", "x": 120, "y": 24, "width": 88 },
                    { "thing": "Stone", "x": 184, "y": 64 },
                    { "thing": "CastleBlock", "x": 184, "y": 56 },
                    { "thing": "Stone", "x": 192, "y": 88, "width": 1088 },
                    { "macro": "Water", "x": 208, "width": 24 },
                    { "macro": "Floor", "x": 232, "y": 24, "width": 8 },
                    { "macro": "Floor", "x": 240, "y": 16, "width": 8 },
                    { "thing": "CastleBlock", "x": 240, "y": 24, "fireballs": 6, "speed": -1 },
                    { "thing": "Block", "x": 240, "y": 56, "contents": "Mushroom" },
                    { "macro": "Floor", "x": 248, "y": 24, "width": 8 },
                    { "macro": "Water", "x": 256, "width": 24 },
                    { "macro": "Floor", "x": 280, "y": 0, "width": 744 },
                    { "thing": "Stone", "x": 280, "y": 32, "width": 296 },
                    { "thing": "Stone", "x": 280, "y": 24, "width": 552, "height": 24 },
                    { "thing": "Stone", "x": 296, "y": 80, "width": 280, "height": 24 },
                    { "thing": "CastleBlock", "x": 296, "y": 56 },
                    { "thing": "CastleBlock", "x": 392, "y": 56, "fireballs": 6 },
                    { "thing": "CastleBlock", "x": 480, "y": 56, "fireballs": 6 },
                    { "thing": "CastleBlock", "x": 536, "y": 56, "fireballs": 6 },
                    { "thing": "CastleBlock", "x": 608, "y": 32, "fireballs": 6 },
                    { "thing": "CastleBlock", "x": 640, "y": 72 },
                    { "thing": "Stone", "x": 640, "y": 80 },
                    { "thing": "CastleBlock", "x": 672, "y": 32, "fireballs": 6 },
                    { "thing": "CastleBlock", "x": 704, "y": 72, "fireballs": 6, "direction": 1 },
                    { "thing": "Stone", "x": 704, "y": 80 },
                    { "thing": "CastleBlock", "x": 736, "y": 32 },
                    { "thing": "Stone", "x": 776, "y": 80, "width": 56, "height": 16 },
                    { "macro": "Fill", "thing": "Block", "x": 848, "y": 32, "xnum": 3, "xwidth": 24, "hidden": true },
                    { "macro": "Fill", "thing": "Block", "x": 856, "y": 64, "xnum": 3, "xwidth": 24, "hidden": true },
                    { "thing": "Stone", "x": 928, "y": 24, "width": 32, "height": 24 },
                    { "thing": "Stone", "x": 984, "y": 24, "width": 40, "height": 24 },
                    { "thing": "Stone", "x": 984, "y": 80, "width": 40, "height": 16 },
                    { "macro": "EndInsideCastle", "x": 1024 },
                    { "thing": "Platform", "x": 1108, "y": 56, "width": 16, "sliding": true, "begin": 1080, "end": 1112, "nocollidechar": true }
                ]
            }
        ]
    },
    "2-1": {
        "locations": [
            { "entry": "Plain" },
            { "xloc": 1260 },
            { "entry": "PipeVertical" },
            { "area": 1/*, "entry": "Cloud"*/ },
            { "area": 2 }
        ],
        "areas": [
            {
                "setting": "Overworld",
                "creation": [
                    { "location": 0 },
                    { "macro": "Floor", "width": 736 },
                    { "macro": "Pattern", "pattern": "BackFence", "repeat": 2 },
                    { "thing": "Brick", "x": 120, "y": 32 },
                    { "thing": "Brick", "x": 128, "y": 32, "contents": "Mushroom" },
                    { "thing": "Brick", "x": 136, "y": 32 },
                    { "thing": "Stone", "x": 160, "y": 8 },
                    { "thing": "Stone", "x": 168, "y": 16, "height": 16 },
                    { "thing": "Stone", "x": 176, "y": 24, "height": 24 },
                    { "thing": "Stone", "x": 184, "y": 32, "height": 32 },
                    { "thing": "Stone", "x": 192, "y": 40, "height": 40 },
                    { "thing": "Goomba", "x": 192, "y": 48 },
                    { "thing": "Block", "x": 224, "y": 32, "hidden": true },
                    { "thing": "Block", "x": 224, "y": 64, "contents": "Mushroom1Up", "hidden": true },
                    { "macro": "Fill", "thing": "Brick", "x": 232, "y": 64, "xnum": 3 },
                    { "thing": "Koopa", "x": 256, "y": 12 },
                    { "thing": "Koopa", "x": 264, "y": 12 },
                    { "thing": "Stone", "x": 272, "y": 32, "height": 32 },
                    { "thing": "Stone", "x": 280, "y": 16, "height": 16 },
                    { "thing": "Goomba", "x": 336, "y": 8 },
                    { "thing": "Goomba", "x": 348, "y": 8 },
                    { "macro": "Pipe", "x": 368, "height": 32, "Piranha": "true" },
                    { "thing": "Block", "x": 424, "y": 32, "contents": "Mushroom" },
                    { "macro": "Fill", "thing": "Block", "x": 424, "y": 64, "xnum": 5 },
                    { "macro": "Fill", "thing": "Block", "x": 432, "y": 32, "xnum": 4 },
                    { "thing": "Koopa", "x": 440, "y": 44 },
                    { "thing": "Goomba", "x": 472, "y": 8 },
                    { "thing": "Goomba", "x": 484, "y": 8 },
                    { "thing": "Koopa", "x": 528, "y": 12 },
                    { "macro": "Fill", "thing": "Goomba", "x": 544, "y": 8, "xnum": 3, "xwidth": 12 },
                    { "thing": "Brick", "x": 544, "y": 32 },
                    { "thing": "Brick", "x": 552, "y": 64, "contents": "Star" },
                    { "thing": "Brick", "x": 560, "y": 64, "xnum": 3 },
                    { "macro": "Pipe", "x": 592, "height": 32, "piranha": true },
                    { "macro": "Fill", "thing": "Block", "x": 632, "y": 32, "xnum": 4 },
                    { "macro": "Fill", "thing": "Brick", "x": 648, "y": 64, "xnum": 2 },
                    { "thing": "Brick", "x": 664, "y": 64, "contents": ["Vine", { "entrance": 3 }] },
                    { "macro": "Fill", "thing": "Brick", "x": 672, "y": 64, "xnum": 2 },
                    { "macro": "Fill", "thing": "Block", "x": 680, "y": 32, "xnum": 3 },
                    { "macro": "Fill", "thing": "Goomba", "x": 704, "y": 8, "xnum": 3, "xwidth": 12 },
                    { "macro": "Fill", "thing": "Brick", "x": 736, "y": 64, "xnum": 4 },
                    { "macro": "Floor", "x": 768, "width": 80 },
                    { "macro": "Pattern", "pattern": "BackFenceMin", "x": 768 },
                    { "thing": "Goomba", "x": 820, "y": 40 },
                    { "macro": "Pipe", "x": 824, "height": 32, "piranha": true, "entrance": 4 },
                    { "macro": "Floor", "x": 872, "width": 240 },
                    { "thing": "Goomba", "x": 916, "y": 24 },
                    { "macro": "Pipe", "x": 920, "height": 16, "piranha": true, "exit": 2 },
                    { "thing": "Goomba", "x": 962, "y": 8 },
                    { "macro": "Pipe", "x": 976, "height": 32, "piranha": true },
                    { "thing": "Brick", "x": 1000, "y": 64, "contents": "Mushroom" },
                    { "macro": "Fill", "thing": "Brick", "x": 1008, "y": 64, "xnum": 3 },
                    { "macro": "Pipe", "x": 1008, "height": 24 },
                    { "macro": "Pipe", "x": 1040, "height": 40, "piranha": true },
                    { "macro": "Floor", "x": 1136, "width": 80 },
                    { "macro": "Pattern", "pattern": "BackFence", "x": 1152, "repeat": 2 },
                    { "thing": "Koopa", "x": 1200, "y": 36, "jumping": true },
                    { "macro": "Floor", "x": 1232, "width": 576 },
                    { "thing": "Stone", "x": 1232, "y": 24, "height": 24 },
                    { "thing": "Brick", "x": 1288, "y": 32, "contents": "Coin" },
                    { "macro": "Fill", "thing": "Goomba", "x": 1296, "y": 8, "xnum": 2, "xwidth": 12 },
                    { "macro": "Fill", "thing": "Brick", "x": 1312, "y": 64, "xnum": 5 },
                    { "macro": "Fill", "thing": "Koopa", "x": 1352, "y": 12, "xnum": 2, "xwidth": 16 },
                    { "thing": "Block", "x": 1360, "y": 32 },
                    { "thing": "Block", "x": 1374, "y": 64, "contents": "Mushroom" },
                    { "macro": "Pipe", "x": 1408, "height": 24, "piranha": true },
                    { "thing": "Koopa", "x": 1480, "y": 12 },
                    { "macro": "Fill", "thing": "Brick", "x": 1480, "y": 32, "xnum": 2 },
                    { "thing": "Block", "x": 1488, "y": 64, "contents": "Coin", "hidden": true },
                    // { "thing": "Springboard", "x": 1504, "y": 14.5 },
                    { "macro": "Fill", "thing": "Stone", "x": 1520, "y": 80, "xnum": 2, "height": 80 },
                    { "macro": "EndOutsideCastle", "x": 1596 }
                ]
            },
            {
                "setting": "Sky",
                "exit": 1,
                "creation": [
                    { "location": 3 },
                    { "thing": "Stone", "width": 32 },
                    { "thing": "Stone", "x": 40, "width": 456 },
                    { "macro": "Fill", "thing": "Coin", "x": 121, "y": 55, "xnum": 16 },
                    { "thing": "Platform", "x": 128, "y": 24, "width": 24, "transport": true },
                    { "macro": "Fill", "thing": "Coin", "x": 257, "y": 71, "xnum": 3 },
                    { "macro": "Fill", "thing": "Coin", "x": 289, "y": 63, "xnum": 16 },
                    { "macro": "Fill", "thing": "Coin", "x": 425, "y": 71, "xnum": 3 },
                    { "macro": "Fill", "thing": "Coin", "x": 553, "y": 7, "xnum": 3 }
                ]
            },
            {
                "setting": "Underworld",
                "creation": [
                    { "location": 4 },
                    { "macro": "Ceiling", "x": 32, "width": 56 },
                    { "macro": "Floor", "width": 136 },
                    { "macro": "Fill", "thing": "Brick", "y": 8, "ynum": 11 },
                    { "macro": "Fill", "thing": "Brick", "x": 32, "y": 8, "xnum": 7, "ynum": 3 },
                    { "macro": "Fill", "thing": "Coin", "x": 33, "y": 31, "xnum": 7, "ynum": 2, "yheight": 16 },
                    { "macro": "Fill", "thing": "Coin", "x": 41, "y": 63, "xnum": 5 },
                    { "thing": "PipeHorizontal", "x": 104, "y": 16, "entrance": 2 },
                    { "thing": "PipeVertical", "x": 120, "y": 88, "height": 88 }
                ]
            }
        ]
    },
    "2-2": {
        "locations": [
            { "entry": "Walking" },
            { "area": 1 },
            { "area": 2, "entry": "PipeVertical" }
        ],
        "areas": [
            {
                "setting": "Overworld",
                "creation": [
                    { "location": 0 },
                    { "macro": "Pattern", "pattern": "BackCloud", "y": 4, "repeat": 2 },
                    { "macro": "Floor", "width": 192 },
                    { "thing": "PipeHorizontal", "x": 80, "y": 16, "transport": 1 },
                    { "macro": "Pipe", "x": 96, "height": 32 }
                ]
            }, 
            {
                "setting": "Underwater",
                "underwater": true,
                "creation": [
                    { "location": 1 },
                    { "macro": "Floor", "width": 536 }, 
                    { "thing": "Coral", "x": 96, "y": 24, "height": 24 },
                    { "macro": "Fill", "thing": "Coin", "x": 121, "y": 7, "xnum": 2 },
                    { "thing": "Stone", "x": 152, "y": 32, "width": 24 },
                    { "thing": "Blooper", "x": 184, "y": 16 },
                    { "macro": "Fill", "thing": "Coin", "x": 224, "y": 64, "xnum": 3 },
                    { "thing": "Coral", "x": 272, "y": 40, "height": 80 },
                    { "macro": "Fill", "thing": "Coin", "x": 296, "y": 7, "xnum": 3 },
                    { "thing": "Stone", "x": 344, "y": 32, "width": 16 },
                    { "thing": "Coral", "x": 344, "y": 48, "height": 16 },
                    { "thing": "Blooper", "x": 376, "y": 32 },
                    { "thing": "Coral", "x": 408, "y": 32, "height": 32 },
                    { "thing": "Blooper", "x": 448, "y": 24 },
                    { "thing": "Stone", "x": 520, "y": 24, "height": 24 },
                    { "thing": "Stone", "x": 528, "y": 40, "height": 40 },
                    { "macro": "Fill", "thing": "Coin", "x": 546, "y": 23, "xnum": 3 },
                    { "macro": "Floor", "x": 576, "width": 480 },
                    { "thing": "Stone", "x": 576, "y": 40, "height": 40 },
                    { "thing": "Stone", "x": 584, "y": 24, "height": 24 },
                    { "thing": "CheepCheep", "x": 616, "y": 24 },
                    { "thing": "Stone", "x": 632, "y": 24, "width": 16, "height": 24 },
                    { "thing": "Stone", "x": 632, "y": 88, "width": 16, "height": 24 },
                    { "thing": "CheepCheep", "x": 640, "y": 48 },
                    { "thing": "CheepCheep", "x": 656, "y": 16 },
                    { "thing": "Stone", "x": 664, "y": 64, "width": 24 },
                    { "thing": "Blooper", "x": 672, "y": 40 },
                    { "thing": "Coral", "x": 672, "y": 80, "height": 16 },
                    { "thing": "Coral", "x": 720, "y": 24, "height": 24 },
                    { "thing": "Blooper", "x": 760, "y": 80 },
                    { "thing": "CheepCheep", "x": 760, "y": 56 },
                    { "thing": "CheepCheep", "x": 784, "y": 80, "smart": true },
                    { "macro": "Fill", "thing": "Coin", "x": 816, "y": 15, "xnum": 3 },
                    { "thing": "Stone", "x": 824, "y": 32, "width": 16 },
                    { "thing": "Coral", "x": 824, "y": 64, "height": 32 },
                    { "thing": "Blooper", "x": 848, "y": 16 },
                    { "macro": "Fill", "thing": "Coin", "x": 912, "y": 55, "xnum": 3 },
                    { "thing": "Stone", "x": 928, "y": 40, "width": 16 },
                    { "thing": "CheepCheep", "x": 944, "y": 72 },
                    { "thing": "Coral", "x": 968, "y": 32, "height": 32 },
                    { "thing": "CheepCheep", "x": 1032, "y": 24, "smart": true },
                    { "thing": "Stone", "x": 1040, "y": 32, "height": 32 },
                    { "thing": "Stone", "x": 1048, "y": 16, "height": 16 },
                    { "thing": "CheepCheep", "x": 1056, "y": 16 },
                    { "thing": "Stone", "x": 1056, "y": 88, "height": 24 },
                    { "thing": "Stone", "x": 1064, "y": 72, "width": 64 },
                    { "thing": "Coin", "x": 1073, "y": 15 },
                    { "macro": "Fill", "thing": "Coin", "x": 1080, "y": 7, "xnum": 3 },
                    { "thing": "Coin", "x": 1105, "y": 15 },
                    { "thing": "CheepCheep", "x": 1100, "y": 40 },
                    { "macro": "Floor", "x": 1128, "width": 136 },
                    { "thing": "Stone", "x": 1128, "y": 16, "height": 16 },
                    { "thing": "Stone", "x": 1136, "y": 32, "height": 32 },
                    { "thing": "CheepCheep", "x": 1160, "y": 32 },
                    { "thing": "Coral", "x": 1184, "y": 16, "height": 16 },
                    { "thing": "Coral", "x": 1200, "y": 24, "height": 24 },
                    { "thing": "CheepCheep", "x": 1206, "y": 56, "smart": true },
                    { "thing": "Stone", "x": 1256, "y": 64, "height": 64 },
                    { "thing": "Stone", "x": 1264, "y": 64, "width": 16 },
                    { "macro": "Fill", "thing": "Coin", "x": 1281, "y": 7, "xnum": 3, "ynum": 2, "yheight": 24 },
                    { "thing": "Stone", "x": 1304, "y": 64, "width": 16 },
                    { "thing": "Stone", "x": 1320, "y": 64, "height": 64 },
                    { "macro": "Floor", "x": 1320, "width": 320 },
                    { "thing": "CheepCheep", "x": 1320, "y": 80 },
                    { "thing": "CheepCheep", "x": 1344, "y": 16 },
                    { "macro": "Fill", "thing": "Stone", "x": 1384, "y": 32, "ynum": 2, "yheight": 32, "width": 40 },
                    { "thing": "Coral", "x": 1392, "y": 80, "height": 16 },
                    { "thing": "CheepCheep", "x": 1408, "y": 40 },
                    { "macro": "Fill", "thing": "Stone", "x": 1448, "y": 32, "ynum": 2, "yheight": 32, "width": 32 },
                    { "thing": "CheepCheep", "x": 1472, "y": 72, "smart": true },
                    { "thing": "CheepCheep", "x": 1496, "y": 48, "smart": true },
                    { "thing": "Stone", "x": 1488, "y": 8, "width": 40 },
                    { "thing": "Stone", "x": 1496, "y": 16, "width": 32 },
                    { "thing": "Stone", "x": 1504, "y": 24, "width": 24 },
                    { "thing": "Stone", "x": 1512, "y": 32, "width": 16 },
                    { "thing": "Stone", "x": 1512, "y": 88, "width": 16, "height": 32 },
                    { "thing": "PipeHorizontal", "x": 1520, "y": 48, "transport": 2, "small": true },
                    { "thing": "Stone", "x": 1528, "y": 88, "width": 112, "height": 88 }
                ]
            },
            {
                "setting": "Overworld",
                "creation": [
                    { "location": 4 },
                    { "macro": "Floor", "width": 464 },
                    { "macro": "Pipe", "height": 16, "piranha": true, "transport": 4 },
                    { "macro": "Pattern", "pattern": "BackRegular", "x": 104, },
                    { "thing": "Stone", "x": 16, "y": 8 },
                    { "thing": "Stone", "x": 24, "y": 16, "height": 16 },
                    { "thing": "Stone", "x": 32, "y": 24, "height": 24 },
                    { "thing": "Stone", "x": 40, "y": 32, "height": 32 },
                    { "thing": "Stone", "x": 48, "y": 40, "height": 40 },
                    { "thing": "Stone", "x": 56, "y": 48, "height": 48 },
                    { "thing": "Stone", "x": 64, "y": 56, "height": 56 },
                    { "thing": "Stone", "x": 72, "y": 64, "height": 64 },
                    { "macro": "EndOutsideCastle", "x": 148 }
                ]
            }
        ]
    },
    "2-3": {
        "time": 300,
        "locations": [
            { "entry": "Plain" }
        ],
        "areas": [
            {
                "setting": "Overworld",
                "creation": [
                    { "location": 0 },
                    { "macro": "Floor", "width": 56 },
                    { "macro": "Pattern", "pattern": "BackCloud", "y": 4, "repeat": 5 },
                    { "macro": "CheepsStart", "x": 64 },
                    { "macro": "Tree", "x": 64, "width": 64 },
                    { "thing": "Stone", "x": 80, "y": 8 },
                    { "thing": "Stone", "x": 88, "y": 16, "height": 16 },
                    { "thing": "Stone", "x": 96, "y": 24, "height": 24, "width": 24 },
                    { "macro": "Bridge", "x": 120, "y": 24, "width": 136, "end": true },
                    { "macro": "Bridge", "x": 256, "y": 24, "width": 128, "end": true },
                    { "macro": "Fill", "thing": "Coin", "x": 290, "y": 63, "xnum": 4 },
                    { "macro": "Bridge", "x": 384, "y": 24, "width": 128, "end": true },
                    { "macro": "Fill", "thing": "Coin", "x": 441, "y": 63, "xnum": 3, "xwidth": 16 },
                    { "macro": "Fill", "thing": "Coin", "x": 449, "y": 55, "xnum": 2, "xwidth": 16 },
                    { "macro": "Bridge", "x": 544, "y": 24, "width": 96, "begin": true, "end": true },
                    { "macro": "Bridge", "x": 672, "y": 24, "width": 96, "begin": true, "end": true },
                    { "macro": "Fill", "thing": "Coin", "x": 777, "y": 63, "xnum": 3 },
                    { "macro": "Bridge", "x": 792, "y": 32, "width": 56, "begin": true, "end": true },
                    { "thing": "Block", "x": 816, "y": 64, "contents": "Mushroom" },
                    { "macro": "Fill", "thing": "Coin", "x": 865, "y": 63, "xnum": 3 },
                    { "macro": "Tree", "x": 896, "width": 64 },
                    { "macro": "Bridge", "x": 976, "y": 24, "width": 24 },
                    { "macro": "Bridge", "x": 1016, "y": 24, "width": 136, "begin": true, "end": true },
                    { "macro": "Fill", "thing": "Coin", "x": 1064, "y": 63, "xnum": 6 },
                    { "macro": "Bridge", "x": 1168, "y": 8, "width": 80, "begin": true, "end": true },
                    { "macro": "Fill", "thing": "Coin", "x": 1193, "y": 39, "xnum": 4 },
                    { "macro": "Bridge", "x": 1272, "y": 24, "width": 80, "begin": true, "end": true },
                    { "macro": "Bridge", "x": 1368, "y": 24, "width": 16 },
                    { "macro": "Fill", "thing": "Coin", "x": 1385, "y": 55, "xnum": 6 },
                    { "macro": "Bridge", "x": 1400, "y": 24, "width": 16 },
                    { "macro": "Bridge", "x": 1432, "y": 24, "width": 16 },
                    { "macro": "Bridge", "x": 1464, "y": 24, "width": 80, "begin": true },
                    { "macro": "Tree", "x": 1536, "width": 104 },
                    { "thing": "Stone", "x": 1544, "y": 24, "width": 16, "height": 24 },
                    { "thing": "Stone", "x": 1560, "y": 16, "height": 16 },
                    { "thing": "Stone", "x": 1568, "y": 8 },
                    { "macro": "CheepsStop" },
                    { "macro": "Floor", "x": 1656, "width": 280 },
                    { "thing": "Stone", "x": 1664, "y": 8 },
                    { "thing": "Stone", "x": 1672, "y": 16, "height": 16 },
                    { "thing": "Stone", "x": 1680, "y": 24, "height": 24 },
                    { "thing": "Stone", "x": 1688, "y": 32, "height": 32 },
                    { "thing": "Stone", "x": 1696, "y": 40, "height": 40 },
                    { "thing": "Stone", "x": 1704, "y": 48, "height": 48 },
                    { "thing": "Stone", "x": 1712, "y": 56, "height": 56 },
                    { "thing": "Stone", "x": 1720, "y": 64, "width": 16, "height": 64 },
                    { "macro": "EndCastleOutside", "x": 1796, "big": true, "wallwidth": 48 }
                ]
            }
        ]
    },
    "2-4": {
        "time": 300,
        "locations": [
            { "entry": "Castle" }
        ],
        "areas": [
            {
                "setting": "Castle",
                "creation": [
                    { "location": 0 },
                    { "macro": "StartInsideCastle", "width": 128 },
                    { "thing": "Stone", "y": 88, "width": 128, "height": 24 },
                    { "thing": "Podoboo", "x": 128, "y": -32 },
                    { "macro": "Water", "x": 128, "width": 128 },
                    { "thing": "Stone", "x": 144, "y": 32, "width": 16 },
                    { "thing": "Stone", "x": 176, "y": 48 },
                    { "thing": "CastleBlock", "x": 184, "y": 48 },
                    { "thing": "Block", "x": 184, "y": 80, "contents": "Mushroom" },
                    { "thing": "Stone", "x": 192, "y": 48 },
                    { "thing": "Stone", "x": 216, "y": 32, "width": 16 },
                    { "thing": "Podoboo", "x": 240, "y": -32 },
                    { "macro": "Floor", "x": 256, "y": -8, "width": 416 },
                    { "thing": "Stone", "x": 256, "y": 24, "width": 16, "height": 32 },
                    { "thing": "Stone", "x": 272, "y": 88, "width": 392, "height": 24 },
                    { "thing": "Stone", "x": 272, "y": 64, "width": 168 },
                    { "thing": "Stone", "x": 272, "width": 72 },
                    { "thing": "Stone", "x": 296, "y": 32, "width": 96 },
                    { "thing": "CastleBlock", "x": 344 },
                    { "thing": "Stone", "x": 352, "width": 88 },
                    { "thing": "CastleBlock", "x": 392, "y": 32, "fireballs": 6 },
                    { "thing": "Stone", "x": 400, "y": 32, "width": 88 },
                    { "thing": "CastleBlock", "x": 440, "y": 64, "fireballs": 6 },
                    { "thing": "CastleBlock", "x": 440 },
                    { "thing": "Stone", "x": 448, "width": 88 },
                    { "thing": "Stone", "x": 448, "y": 64, "width": 216 },
                    { "thing": "CastleBlock", "x": 488, "y": 32, "fireballs": 6 },
                    { "thing": "Stone", "x": 496, "y": 32, "width": 88 },
                    { "thing": "CastleBlock", "x": 536 },
                    { "thing": "Stone", "x": 544, "width": 96 },
                    { "thing": "CastleBlock", "x": 584, "y": 32, "fireballs": 6 },
                    { "thing": "Stone", "x": 640, "y": 24, "width": 32, "height": 32 },
                    { "thing": "CastleBlock", "x": 656, "y": 56, "fireballs": 6 },
                    { "macro": "Floor", "x": 736, "y": 16 },
                    { "thing": "CastleBlock", "x": 736, "y": 24, "fireballs": 6, "direction": 1 },
                    { "macro": "Floor", "x": 744, "y": 24, "width": 48 },
                    { "thing": "Stone", "x": 744, "y": 88, "width": 48, "height": 24 },
                    { "macro": "Floor", "x": 792, "width": 80 },
                    { "macro": "Fill", "thing": "Coin", "x": 817, "y": 7, "xnum": 3, "ynum": 2, "xwidth": 8, "yheight": 32 },
                    { "thing": "CastleBlock", "x": 824, "y": 16 },
                    { "thing": "Stone", "x": 864, "y": 24, "height": 24 },
                    { "macro": "Water", "x": 872, "width": 16 },
                    { "thing": "Stone", "x": 864, "y": 24, "height": 24 },
                    { "macro": "Floor", "x": 888, "y": 24, "width": 16 },
                    { "macro": "Water", "x": 904, "width": 32 },
                    { "macro": "Floor", "x": 920, "width": 104 },
                    { "thing": "Stone", "x": 920, "y": 24, "width": 40, "height": 24 },
                    { "thing": "Stone", "x": 920, "y": 88, "width": 104, "height": 24 },
                    { "macro": "Fill", "thing": "Stone", "x": 976, "y": 24, "xnum": 2, "xwidth": 32, "width": 16, "height": 24 },
                    { "macro": "Fill", "thing": "Brick", "x": 1024, "y": 64, "xnum": 6 },
                    { "macro": "EndInsideCastle", "x": 1024 },
                    { "thing": "Platform", "x": 1084, "y": 56, "width": 16 }
                ]
            }
        ]
    },
    "3-1": {
        "time": 300,
        "locations": [
            { "entry": "Plain" },
            { "entry": "PipeVertical" },
            { "xloc": 1272 },
            { "area": 1 },
            { "area": 2/*, "entry": "Cloud"*/ }
        ],
        "areas": [
            {
                "setting": "Overworld Night Alt",
                "creation": [
                { "location": 0 },
                { "macro": "Floor", "width": 360 },
                { "macro": "Pattern", "pattern": "BackFence", "repeat": 5 },
                { "thing": "Block", "x": 128, "y": 32 },
                { "thing": "Block", "x": 152, "y": 40 },
                { "thing": "Block", "x": 176, "y": 40, "contents": "Mushroom" },
                { "thing": "Koopa", "x": 200, "y": 12, "jumping": true },
                { "macro": "Fill", "thing": "Brick", "x": 208, "y": 32, "xnum": 3 },
                { "thing": "Koopa", "x": 224, "y": 20, "jumping": true },
                { "macro": "Pipe", "x": 256, "height": 24, "piranha": true },
                { "thing": "Goomba", "x": 296, "y": 8 },
                { "macro": "Pipe", "x": 304, "height": 32, "piranha": true, "entrance": 3 },
                { "macro": "Floor", "x": 384, "width": 232 },
                { "macro": "Fill", "thing": "Goomba", "x": 424, "y": 8, "xnum": 3, "xwidth": 12 },
                { "macro": "Pipe", "x": 456, "height": 24, "piranha": true },
                { "thing": "Brick", "x": 488, "y": 32 },
                { "thing": "Koopa", "x": 520, "y": 12 },
                { "macro": "Pipe", "x": 536, "height": 16, "piranha": true, "exit": 1 },
                { "thing": "Stone", "x": 584, "y": 8 },
                { "thing": "Stone", "x": 592, "y": 16, "height": 16 },
                { "thing": "Stone", "x": 600, "y": 24, "height": 24 },
                { "thing": "Stone", "x": 608, "y": 32, "height": 32 },
                { "macro": "Water", "x": 616, "y": 10, "width": 64 },
                { "macro": "Bridge", "x": 616, "y": 32, "width": 64 },
                { "macro": "Fill", "thing": "Goomba", "x": 656, "y": 40, "xnum": 3, "xwidth": 12 },
                { "thing": "Block", "x": 656, "y": 64, "contents": "Mushroom1Up", "hidden": true },
                { "macro": "Floor", "x": 680 },
                { "thing": "Stone", "x": 680, "y": 32, "height": 32 },
                { "macro": "Water", "x": 688, "y": 10, "width": 16 },
                { "macro": "Floor", "x": 704, "width": 320 },
                { "thing": "Stone", "x": 704, "y": 32, "height": 32 },
                { "thing": "Stone", "x": 712, "y": 16, "height": 16 },
                { "thing": "Brick", "x": 720, "y": 64, "contents": "Star" },
                { "macro": "Fill", "thing": "Brick", "x": 728, "y": 64, "xnum": 2 },
                { "macro": "Fill", "thing": "Goomba", "x": 752, "y": 8, "xnum": 2, "xwidth": 12 },
                { "thing": "Koopa", "x": 808, "y": 12 },
                { "macro": "Pipe", "x": 824, "height": 32, "piranha": true },
                { "macro": "Fill", "thing": "Brick", "x": 888, "y": 32, "xnum": 11 },
                { "macro": "Fill", "thing": "Brick", "x": 888, "y": 64, "xnum": 2 },
                { "thing": "HammerBro", "x": 904, "y": 44 },
                { "thing": "Block", "x": 904, "y": 64 },
                { "macro": "Fill", "thing": "Brick", "x": 912, "y": 64, "xnum": 3 },
                { "thing": "HammerBro", "x": 936, "y": 12 },
                { "thing": "Block", "x": 936, "y": 64, "contents": "Mushroom" },
                { "macro": "Fill", "thing": "Brick", "x": 944, "y": 64, "xnum": 3 },
                // { "thing": "Springboard", "x": 1008, "y": 14.5 },
                { "macro": "Fill", "thing": "Brick", "x": 1032, "y": 40, "xnum": 3 },
                { "macro": "Fill", "thing": "Brick", "x": 1032, "y": 64, "xnum": 2 },
                { "thing": "Brick", "thing": "Brick", "x": 1048, "y": 64, "contents": ["Vine", { "entrance": 4 }] },
                { "macro": "Floor", "x": 1056, "width": 80 },
                { "thing": "Stone", "x": 1088 },
                { "thing": "Stone", "x": 1096, "y": 16, "height": 16 },
                { "thing": "Stone", "x": 1104, "y": 24, "height": 24 },
                { "thing": "Stone", "x": 1112, "y": 32, "height": 32 },
                { "thing": "Goomba", "x": 1112, "y": 40 },
                { "thing": "Stone", "x": 1120, "y": 40, "height": 40 },
                { "thing": "Goomba", "x": 1120, "y": 48 },
                { "thing": "Stone", "x": 1128, "y": 48, "height": 48 },
                { "macro": "Floor", "x": 1152, "width": 264 },
                { "thing": "Koopa", "x": 1192, "y": 12 },
                { "macro": "Fill", "thing": "Brick", "x": 1200, "y": 32, "xnum": 2, "ynum": 2, "xwidth": 16, "yheight": 32 },
                { "macro": "Fill", "thing": "Block", "x": 1208, "y": 32, "ynum": 2, "yheight": 32 },
                { "thing": "Koopa", "x": 1216, "y": 76 },
                { "macro": "Fill", "thing": "Goomba", "x": 1232, "y": 8, "xnum": 3, "xwidth": 12 },
                { "macro": "Fill", "thing": "Brick", "x": 1240, "y": 32, "xnum": 2, "ynum": 2, "xwidth": 16, "yheight": 32 },
                { "thing": "Block", "x": 1248, "y": 32, "contents": "Mushroom" },
                { "thing": "Block", "x": 1248, "y": 64 },
                { "thing": "Koopa", "x": 1320, "y": 12, "jumping": true },
                { "thing": "Brick", "x": 1328, "y": 32 },
                { "thing": "Brick", "x": 1336, "y": 32, "contents": "Coin" },
                { "thing": "Koopa", "x": 1344, "y": 18, "jumping": true },
                { "macro": "Fill", "thing": "Brick", "x": 1344, "y": 32, "xnum": 3 },
                { "thing": "Koopa", "x": 1360, "y": 44 },
                { "thing": "Koopa", "x": 1368, "y": 12, "jumping": true },
                { "thing": "Stone", "x": 1392, "y": 24, "height": 24 },
                { "thing": "Stone", "x": 1400, "y": 48, "height": 48 },
                { "macro": "Floor", "x": 1440, "width": 320 },
                { "thing": "Stone", "x": 1464, "y": 8 },
                { "thing": "Stone", "x": 1472, "y": 16, "height": 16 },
                { "thing": "Stone", "x": 1480, "y": 24, "height": 24 },
                { "thing": "Stone", "x": 1488, "y": 32, "height": 32 },
                { "thing": "Stone", "x": 1496, "y": 40, "height": 40 },
                { "thing": "Stone", "x": 1504, "y": 48, "height": 48 },
                { "thing": "Koopa", "x": 1504, "y": 60 },
                { "thing": "Stone", "x": 1512, "y": 56, "height": 56 },
                { "thing": "Stone", "x": 1520, "y": 64, "width": 16, "height": 64 },
                { "thing": "Koopa", "x": 1528, "y": 76 },
                { "macro": "EndOutsideCastle", "x": 1596 }
            ]
        },
        {
            "setting": "Underworld",
            "creation": [
                { "location": 3 },
                { "macro": "Floor", "width": 136 },
                { "macro": "Fill", "thing": "Brick", "y": 8, "ynum": 11 },
                { "macro": "Fill", "thing": "Brick", "x": 24, "y": 40, "xnum": 2, "ynum": 4, "xwidth": 72 },
                { "macro": "Fill", "thing": "Brick", "x": 32, "y": 32, "xnum": 2, "xwidth": 56 },
                { "macro": "Fill", "thing": "Brick", "x": 32, "y": 56, "xnum": 2, "ynum": 2, "xwidth": 56 },
                { "macro": "Fill", "thing": "Coin", "x": 33, "y": 39, "xnum": 2, "xwidth": 56 },
                { "macro": "Fill", "thing": "Brick", "x": 40, "y": 40, "xnum": 2, "xwidth": 40 },
                { "thing": "Brick", "x": 40, "y": 64, "contents": "Mushroom" },
                { "macro": "Fill", "thing": "Coin", "x": 41, "y": 47, "xnum": 2, "xwidth": 40 },
                { "macro": "Fill", "thing": "Brick", "x": 48, "y": 48, "xnum": 2, "xwidth": 24 },
                { "macro": "Fill", "thing": "Coin", "x": 49, "y": 55, "xnum": 2, "ynum": 2, "xwidth": 24, "yheight": 16 },
                { "macro": "Fill", "thing": "Brick", "x": 56, "y": 56, "xnum": 2, "ynum": 2 },
                { "macro": "Fill", "thing": "Coin", "x": 57, "y": 71, "xnum": 2, "ynum": 2 },
                { "thing": "Brick", "x": 80, "y": 64 },
                { "thing": "PipeHorizontal", "x": 104, "y": 16, "entrance": 1 },
                { "thing": "PipeVertical", "x": 120, "y": 88, "height": 88 }
            ]
        },
        {
            "setting": "Sky Night",
            "exit": 2,
            "creation": [
                { "location": 4 },
                { "thing": "Stone", "width": 32 },
                { "thing": "Stone", "x": 40, "width": 624 },
                { "thing": "Platform", "x": 128, "y": 24, "width": 24, "transport": true },
                { "macro": "Fill", "thing": "Coin", "x": 121, "y": 55, "xnum": 16 },
                { "thing": "Stone", "x": 256, "y": 40 },
                { "macro": "Fill", "thing": "Coin", "x": 273, "y": 55, "xnum": 16 },
                { "thing": "Stone", "x": 408, "y": 48, "height": 16 },
                { "macro": "Fill", "thing": "Coin", "x": 425, "y": 63, "xnum": 7 },
                { "thing": "Stone", "x": 488, "y": 48, "height": 16 },
                { "thing": "Stone", "x": 536, "y": 56, "width": 16 },
                { "macro": "Fill", "thing": "Stone", "x": 568, "y": 56, "xnum": 5, "xwidth": 16 },
                { "macro": "Fill", "thing": "Coin", "x": 569, "y": 63, "xnum": 10 },
                { "macro": "Fill", "thing": "Coin", "x": 681, "y": 15, "xnum": 3 }
                ]
            }
        ]
    },
    "3-2": {
        "time": 300,
        "locations": [
            { "entry": "Plain" }
        ],
        "areas": [
            {
                "setting": "Overworld Night Alt",
                "creation": [
                    { "location": 0 },
                    { "macro": "Pattern", "pattern": "BackFence",  "x": -384, "repeat": 6 },
                    { "macro": "Floor", "width": 640 },
                    { "thing": "Koopa", "x": 136, "y": 12 },
                    { "macro": "Fill", "thing": "Goomba", "x": 192, "y": 8, "xnum": 3, "xwidth": 12 },
                    { "macro": "Fill", "thing": "Koopa", "x": 264, "y": 12, "xnum": 3, "xwidth": 12 },
                    { "macro": "Fill", "thing": "Koopa", "x": 344, "y": 12, "xnum": 2, "xwidth": 12 },
                    { "thing": "Stone", "x": 392, "y": 8 },
                    { "macro": "Fill", "thing": "Coin", "x": 441, "y": 31, "xnum": 3, "xwidth": 8 },
                    { "thing": "Stone", "x": 480, "y": 24, "height": 24 },
                    { "thing": "Block", "x": 480, "y": 56, "contents": "Mushroom" },
                    { "thing": "Koopa", "x": 528, "y": 12 },
                    { "macro": "Fill", "thing": "Goomba", "x": 568, "y": 8, "xnum": 3, "xwidth": 12 },
                    { "thing": "Stone", "x": 600, "y": 16, "height": 16 },
                    { "thing": "Brick", "x": 616, "y": 32, "contents": "Coin" },
                    { "thing": "Brick", "x": 616, "y": 64, "contents": "Star" },
                    { "thing": "Koopa", "x": 624, "y": 12 },
                    { "thing": "Stone", "x": 632, "y": 16, "height": 16 },
                    { "macro": "Floor", "x": 656, "width": 328 },
                    { "thing": "Koopa", "x": 736, "y": 34, "jumping": true },
                    { "thing": "Koopa", "x": 888, "y": 12 },
                    { "macro": "Fill", "thing": "Goomba", "x": 952, "y": 8, "xnum": 3, "xwidth": 12 },
                    { "macro": "Floor", "x": 1000, "width": 24 },
                    { "thing": "Stone", "x": 1008, "y": 16, "height": 16 },
                    { "thing": "Brick", "x": 1008, "y": 56 },
                    { "macro": "Floor", "x": 1040, "width": 725 },
                    { "thing": "Koopa", "x": 1072, "y": 12 },
                    { "macro": "Fill", "thing": "Koopa", "x": 1120, "y": 12, "xnum": 3, "xwidth": 12 },
                    { "macro": "Fill", "thing": "Koopa", "x": 1200, "y": 12, "xnum": 2, "xwidth": 12 },
                    { "macro": "Fill", "thing": "Koopa", "x": 1296, "y": 12, "xnum": 3, "xwidth": 12 },
                    { "macro": "Fill", "thing": "Coin", "x": 1345, "y": 55, "xnum": 4, "xwidth": 8 },
                    { "macro": "Pipe", "x": 1352, "height": 24, "pirhana": true },
                    { "thing": "Koopa", "x": 1400, "y": 12 },
                    { "macro": "Fill", "thing": "Goomba", "x": 1432, "y": 8, "xnum": 3, "xwidth": 12 },
                    { "macro": "Fill", "thing": "Goomba", "x": 1504, "y": 8, "xnum": 3, "xwidth": 12 },
                    { "thing": "Stone", "x": 1536, "y": 8 },
                    { "thing": "Stone", "x": 1544, "y": 16, "height": 16 },
                    { "thing": "Stone", "x": 1552, "y": 24, "height": 24 },
                    { "thing": "Stone", "x": 1560, "y": 32, "height": 32 },
                    { "thing": "Stone", "x": 1568, "y": 40, "height": 40 },
                    { "thing": "Stone", "x": 1576, "y": 48, "height": 48 },
                    { "thing": "Stone", "x": 1584, "y": 56, "height": 56 },
                    { "thing": "Stone", "x": 1592, "y": 64, "width": 16, "height": 64 },
                    { "macro": "EndOutsideCastle", "x": 1668 }
                ]
            }
        ]
    }
});